dist: trusty
group: travis_latest
sudo: false

language: python
cache: pip

matrix:
    fast_finish: true

    include:
        - python: '2.7'
          env: TOXENV=py27
        - python: '3.4'
          env: TOXENV=py34
        - python: '3.5'
          env: TOXENV=py35
        - python: '3.6'
          env: TOXENV=py36
        - python: '3.6-dev'
          env: TOXENV=py36

        - python: "3.6"
          env: TOXENV=docs
        - python: "3.6"
          env: TOXENV=linting
        - python: "3.6"
          env: TOXENV=manifest

    allow_failures:
        python: '3.6-dev'

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install gfortran -y
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov

notifications:
    email: false
